name: Deploy to EdgeOneCN

on:
  push:
    branches:
      - main  # 监听 main 分支的推送
    paths:
      - 'config/**'
      - 'announce/**'
      - '.github/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 部署到 EdgeOne Pages CN
        run: npx edgeone pages deploy ./ -n ghpccn -t ${{ secrets.EDGEONE_API_TOKEN_CN }}
        env:
          EDGEONE_API_TOKEN_CN: ${{ secrets.EDGEONE_API_TOKEN_CN }}
